# MM _config.yml https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
# - to view on Github set branch to gh-pages-3.1.6
# Site Information
title: Technology and Balancing Life
email: tuborgjunior@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Quick musings on technology mixed with some biking, kayaking, skiing and skating.
baseurl: "/balance" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Aqvavit
github_username:  Gajol
linkedin_username: nielsencanada

# as per jekyll https://jekyllrb.com/docs/permalinks/, and
# as per MM https://mmistakes.github.io/minimal-mistakes/docs/navigation/
permalink: /:categories/:title/

include: ["_pages"]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
#  recipes:
#    output: true
#    permalink: /:collection/:path/
#  pets:
#    output: true
#    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/


# theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# https://github.com/benbalter/jekyll-remote-theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# post defaults - https://mmistakes.github.io/minimal-mistakes/docs/posts/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # collections
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
