# Site Information
title: Technology and Balancing Life
email: tuborgjunior@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Quick musings on technology mixed with some biking, kayaking, skiing and skating.
baseurl: "/balance" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Aqvavit
github_username:  Gajol
linkedin_username: nielsencanada

include: ["_pages"]

# theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# https://github.com/benbalter/jekyll-remote-theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# post defaults - https://mmistakes.github.io/minimal-mistakes/docs/posts/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
